// <auto-generated />
namespace Oregon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _261017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_261017));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261618444_26-10-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
