// <auto-generated />
namespace Oregon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ensar1432 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ensar1432));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201808465_Ensar1432"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
