// <auto-generated />
namespace Oregon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _211017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_211017));
        
        string IMigrationMetadata.Id
        {
            get { return "201710211131442_21-10-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
